---
- hosts: localhost
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present

    - name: Install Docker CLI
      apt:
        name: docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Create a custom Docker network
      docker_network:
        name: n8n_network
        state: present

    - name: Create Docker n8n volume
      community.docker.docker_volume:
        name: n8n_data
        state: present

    - name: Run n8n container
      community.docker.docker_container:
        name: n8n
        image: docker.n8n.io/n8nio/n8n
        state: started
        networks:
          - name: n8n_network
        ports:
          - "5678:5678"
        volumes:
          - "n8n_data:/home/node/.n8n"
        auto_remove: true
        interactive: no
        tty: true
        detach: yes

    - name: Create nginx volume
      docker_volume:
        name: nginx-data
        driver: local

    - name: Create Nginx reverse proxy configuration
      copy:
        dest: "/var/lib/docker/volumes/nginx-data/_data/n8n.conf"
        content: |
          server {
              listen 443 ssl;
              server_name localhost;

              ssl_certificate /etc/nginx/ssl/mycert.crt;
              ssl_certificate_key /etc/nginx/ssl/mykey.key;

              location / {
                  proxy_pass http://n8n:5678;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Ensure default Nginx config is removed
      file:
        path: "/var/lib/docker/volumes/nginx-data/_data/default.conf"
        state: absent

    - name: Copy certificates
      copy:
        src: "{{ playbook_dir }}/certs/"
        dest: "/var/lib/docker/volumes/nginx-data/_data/certs/"

    - name: Run Nginx container with custom configuration and certificates
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        networks:
          - name: n8n_network
        ports:
          - "443:443"
        volumes:
          - "/var/lib/docker/volumes/nginx-data/_data/certs:/etc/nginx/ssl:ro"
          - "nginx-data:/etc/nginx/conf.d"
